name: "automatic-tag-release"

on:
  workflow_dispatch:
    inputs:
      release_type:
        type: choice
        description: 'Release type'
        required: true
        options: 
          - patch
          - minor
          - major
        default: 'patch'

jobs:
  tagged-release:
    name: "ReleaseTag"
    runs-on: "ubuntu-latest"

    steps:
      # ...
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup git-chglog environment
        uses: Bpazy/setup-git-chglog@v1
        with:
          git-chglog-version: '0.15.1'

      - name: Generate Changelog
        env:
          RELEASE_TYPE: ${{ inputs.release_type }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          make changelog
          make release
